import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import { UserProvider } from "@/contexts/useUserContext";
import { useEffect } from "react";
import NavComponent from "@/components/Nav.component";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Despezas Conjuntas",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="pt-br" className="vh-100 vw-100">
      <body className={`${geistSans.variable} ${geistMono.variable} col-12`}>
        <UserProvider>
          <NavComponent />
          <ToastContainer />
          <main className="px-5 pt-3">
            <div className="container-fluid">
              <div className="d-flex flex-wrap">
                {children}
              </div>
            </div>
          </main>
        </UserProvider>
      </body>
      <footer className="text-muted text-center my-5">
        Sistema desenvolvido por Rawlinson Rolim
      </footer>
    </html>
  );
}
